channels:
  - conda-forge
dependencies:
  - ipytone
  - ipywidgets
  - ipyleaflet
  - traittypes
  - jupyterlab
  - numpy
  - matplotlib-base
  - fastscape
  - ipyfastscape
  - ipygany
  - ipycanvas
  - pyvista
  - obspy
  - bqplot
  - scikit-image
  - pandas
  - geopandas
  - pip
  - pip:
    - meanderpy
